manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # duckyb
    - name: duckyb
      url-base: https://github.com/duckyb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: f1b944b1efc01805a769cb2b15797c2c611bcc5f # main
      import: app/west.yml
    - name: urchin-zmk-module
      remote: duckyb
      revision: a3ab64fa7779f82675695f3d7d17f705f840da25 # main
  self:
    path: config
