manifest:
  remotes:
    # zmk official
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # duckyb
    - name: duckyb
      url-base: https://github.com/duckyb
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 11f600d9e52233a038b86069c99c5f7947b7b925 # main
      import: app/west.yml
    - name: urchin-zmk-module
      remote: duckyb
      revision: 57ef72b1fdd3c59c5ac32d2ad3b13289bc17f358 # main
  self:
    path: config
